### ISSUE TITLE
Multiple Browser Windows focus

### ISSUE THREAD

**Issue by studiotbt** [tomasko126/notemark#38] opened 2015-09-29 23:46 UTC
1. add note.
2. open new browser window
3. add note - this will remove the added note even if its a different site.
4. add note again (this will add the same note from the first window.

**Comment by tomasko126** [comment] 2015-10-16 22:58
@studiotbt Cannot reproduce this bug. Can you try to reproduce it again? Thanks!

**Comment by tomasko126** [comment] 2015-12-22 21:28
I am closing this issue. If you are still able to reproduce it, please create a new issue. Thanks!

**Closed as completed by tomasko126** 2015-12-22 21:28 UTC
Labels: bug
