### ISSUE TITLE
After clearing cached images, opening of extension gets delayed. (issue caused by preload?)

### ISSUE THREAD

**Issue by studiotbt** [tomasko126/notemark#20] opened 2015-09-20 19:48 UTC
This seems obvious, because i think it preloads the favicons.
could it open the notes and load the favicons on the fly or something?
no ideas for it at the moment.

**Comment by tomasko126** [comment] 2015-09-21 15:17
@studiotbt How did you clear cached images? Can you write a steps to reproduce? Because I cannot reproduce this bug myself. :)

**Comment by studiotbt** [comment] 2015-09-21 15:23
Chrome > clear browsing data > tick cashed images and files > clear btn.
I just did it, but there was no delay. very strange. 

I get the prob sometimes, maybe because its running local. havent pin pointed yet.

**Comment by tomasko126** [comment] 2015-09-27 12:29
@studiotbt We cannot handle situations, where images are cleared from cache, since caching handles browser. Nothing to really do with this, therefore I am closing this issue now.

**Closed as completed by tomasko126** 2015-09-27 12:29 UTC
Labels: invalid
